name: Create Archive
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'gamesdata.zip'
        exclusions: '*.git*'
        path: 'games'
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "gamesdata.zip"
        tags: 'Release'
            
