name: Create Archive
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'gamesdata.zip'
        path: 'games'
                  
    - name: GH Release
      uses: softprops/action-gh-release@v2.0.4
      with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: gamesdata.zip
          tag_name: github.ref
            
